% disp('Removing redundant inequality constraints...');
% temp_tope = polytope(Aineq, bineq);
% [Aineq, bineq] = double(temp_tope);

%% Parameters for constructor

n_iter = 200; % maximum number of Newton iterationshg
reg = 1e-5;  % regularization Term for Phi
reg_Y = 1e-8;   % new regularization Term for Y
eps_primal = 1e-6; %0.1;
eps_dual = 1e-6; %0.1;
eps_mu = 1e-6; %0.1;

disp(['F_xTheta # of rows: ' num2str(size(F_xTheta,1))]);

%% Write quad.dat and quad.mat
s = d_0;
Q_tilde = Q;
Q_tilde_f = P;
writeParam(...
    N, ...
    quad_bin_fname, ...
    n_iter, ...
    reg, ...
    reg_Y, ...
    eps_primal, ...
    eps_dual, ...
    eps_mu, ...
    A, B, s, ...
    Q_tilde, ...
    Q_tilde_f, ...
    R, ...
    Fx, ...
    fx, ...
    Fu, ...
    fu, ...
    F_xTheta, ...
    F_theta, ...
    f_xTheta, ...
    K ...
    )

%%